version: 2.1

orbs:
  reusable-commands: logan/reusable-commands@0.0.1

jobs:
  build-image:
    machine:
      image: ubuntu-2404:current
    resource_class: large.gen2
    steps:
      - checkout
      - reusable-commands/get_tag:
          orb_pipeline_number: << pipeline.number >>
      - run:
          name: Docker Build
          command: |
            docker build -t imlogang/web-ui:$TAG .
      - reusable-commands/install_trivy
      - reusable-commands/run_trivy:
          scan_image: true
          image_name: "imlogang/web-ui"
      - run: 
          name: Docker Login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Docker Push
          command: |
            docker push imlogang/web-ui:$TAG

  deploy-web-ui:
    resource_class: logan/small
    docker:
      - image: dockerregistry.logangodsey.com/toolbox:latest
    steps:
      - checkout
      - reusable-commands/get_tag:
          orb_pipeline_number: << pipeline.number >>
      - run: 
          name: Helm Upgrade
          command: |
            helm upgrade --install --debug web-ui ./deploy --set image.tag=${TAG} --set circleci.pipelineId=<< pipeline.id >> --set circleci.workflowId=${CIRCLE_WORKFLOW_ID} --set-string circleci.jobNumber=${CIRCLE_BUILD_NUM} -n web-ui -f values.yaml
      - run: 
          name: Watch release
          command: |
            circleci run release plan --environment-name="Microk8s Cluster" --component-name="web-ui" --target-version="${TAG}" --namespace="web-ui" web-ui

  release-web-ui:
    type: release
    plan_name: web-ui

  helm-lint:
    docker: 
      - image: dockerregistry.logangodsey.com/toolbox:latest
    resource_class: logan/small
    steps:
      - checkout
      - run:
          name: helm lint
          command: helm lint ./deploy 

workflows:
  build-and-deploy-web-ui:
    jobs:
      - build-image:
          context:
            - docker_stuff
      - helm-lint
      - deploy-web-ui:
          requires:
            - build-image
            - helm-lint
          serial-group: << pipeline.project.slug >>/deploy-group
          filters:
            branches:
              only:
                - main
      - release-web-ui:
          requires:
            - deploy-web-ui
          filters:
            branches:
              only:
                - main
